### ISSUE TITLE
Erro ao configurar o projeto Client

### ISSUE THREAD

**Issue by emivaljr** [kabrabom/mobile#2]
![screenshot from 2017-07-15 12-31-10](https://user-images.githubusercontent.com/13139796/28239026-7f4f9838-6959-11e7-8de0-1927c13d4ecc.png)
@edu1006 Tenho que fazer mais alguma coisa?

**Comment by emivaljr** [comment]
@edu1006 Tive que rodar o ionic serve primeiro, depois o cordova prepare, agora tá dando outro erro: 
![screenshot from 2017-07-16 10-35-20](https://user-images.githubusercontent.com/13139796/28246473-964253d2-6a12-11e7-94e0-ae9bdfd490b3.png)

**Comment by vlbgomes** [comment]
Não se aplica mais!
